import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Homepage from './Hompage'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PS5",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><Homepage/>{children}</body>
    </html>
  );
}
